services:
  sprobot:
    build:
      context: .
      target: dev
    init: true
    env_file: ./config/config.env

  sprobot-web:
    build:
      context: .
      target: devweb
    env_file: ./config/config.env
    ports:
      - "8080:8080"

  stickybot:
    build:
      context: .
      target: devstickybot
    init: true
    env_file: ./config/config.env

  threadbot:
    build:
      context: .
      target: devthreadbot
    init: true
    env_file: ./config/config.env
